# Generated by Django 3.2.5 on 2021-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0003_alter_musics_fee_near_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='img_url_txt',
            field=models.URLField(),
        ),
    ]
