# Generated by Django 3.2.5 on 2021-11-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0004_alter_musics_img_url_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='composer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musics',
            name='writer',
            field=models.TextField(null=True),
        ),
    ]
