# Generated by Django 3.2.5 on 2021-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0005_auto_20211117_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='img_url_txt',
            field=models.TextField(null=True),
        ),
    ]
