# Generated by Django 3.2.5 on 2021-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0006_alter_musics_img_url_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='cluster_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musics',
            name='cluster_bl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musics',
            name='cluster_bs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musics',
            name='fee_near_year',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musics',
            name='pub_date',
            field=models.TextField(null=True),
        ),
    ]
