# Generated by Django 3.2.5 on 2021-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0007_auto_20211117_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('album', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('writer', models.TextField(null=True)),
                ('composer', models.TextField(null=True)),
                ('fee_near_year', models.IntegerField(default=0)),
                ('img_url_txt', models.TextField(null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('img_url', models.ImageField(default='None.jpg', upload_to='static/img/title_img')),
                ('cluster_a', models.TextField(null=True)),
                ('cluster_bs', models.TextField(null=True)),
                ('cluster_bl', models.TextField(null=True)),
            ],
        ),
    ]
