# Generated by Django 3.2.5 on 2021-11-18 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPP', '0008_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='MusicInfo',
        ),
        migrations.DeleteModel(
            name='Musics',
        ),
    ]
